[project]
name = "myTools"
version = "0.1.0"
description = "A web wrapper for machine programs with support for customizable commands."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
]
